In [1]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/model_data.csv"
)

df.head()

,CustomerId,TotalTransactionAmount,AverageTransactionAmount,TransactionCount,StdTransactionAmount,FraudResult,is_high_risk
0,CustomerId_1,-10000.0,-10000.000000,1,0.000000,0.0,1
1,CustomerId_10,-10000.0,-10000.000000,1,0.000000,0.0,1
2,CustomerId_1001,20000.0,4000.000000,5,6558.963333,0.0,1
3,CustomerId_1002,4225.0,384.090909,11,560.498966,0.0,0
4,CustomerId_1003,20000.0,3333.333333,6,6030.478146,0.0,0

In [2]:
df["is_high_risk"].value_counts()

is_high_risk
0    2315
1    1427
Name: count, dtype: int64

In [3]:
df.describe()

,TotalTransactionAmount,AverageTransactionAmount,TransactionCount,StdTransactionAmount,FraudResult,is_high_risk
count,3.742000e+03,3.742000e+03,3742.000000,3.742000e+03,3742.000000,3742.000000
mean,1.717377e+05,1.571562e+04,25.564404,1.360517e+04,0.005556,0.381347
std,2.717305e+06,1.676991e+05,96.929602,9.689344e+04,0.064539,0.485782
min,-1.049000e+08,-4.250000e+05,1.000000,0.000000e+00,0.000000,0.000000
25%,4.077438e+03,1.000000e+03,2.000000,5.011411e+02,0.000000,0.000000
50%,2.000000e+04,2.583846e+03,7.000000,3.184898e+03,0.000000,0.000000
75%,7.996775e+04,4.877614e+03,20.000000,6.745369e+03,0.000000,1.000000
max,8.345124e+07,8.601821e+06,4091.000000,3.309916e+06,1.000000,1.000000

In [7]:
!python ../src/train.py

2026/06/02 19:43:58 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/06/02 19:43:58 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/06/02 19:44:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/06/02 19:44:41 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

LogisticRegression
Accuracy: 0.6729
Precision: 0.5872
Recall: 0.4825
F1: 0.5298
ROC AUC: 0.7284

RandomForest
Accuracy: 0.6943
Precision: 0.5882
Recall: 0.6643
F1: 0.6240
ROC AUC: 0.7548

Best Model: RandomForest
ROC AUC: 0.7548

2026/06/02 19:46:42 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\DATAEN~1\AppData\Local\Temp\tmpwhoxov36\model\model.pkl, flavor: sklearn). Fall back to return ['scikit-learn==1.8.0', 'cloudpickle==3.1.2']. Set logging level to DEBUG to see the full traceback.

# Model Comparison

Models evaluated:

- Logistic Regression
- Random Forest

Metrics:

- Accuracy
- Precision
- Recall
- F1 Score
- ROC-AUC

MLflow was used to track experiments and compare performance.